name: Python Tests

on: [ push, pull_request ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    name: Python Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'

      # Скачиваем и распаковываем Swagger Coverage CLI через проверенный экшен
      - name: Download Swagger Coverage CLI
        uses: engineerd/configurator@v0.0.10
        with:
          url: "https://github.com"
          from: "swagger-coverage-1.5.0/bin/swagger-coverage-commandline"
          to: "swagger-coverage-commandline"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest ./tests --alluredir=allure-results --disable-warnings
        continue-on-error: true

      - name: Debug - List files
        run: |
          echo "Checking root directory:"
          ls -la
          echo "Checking swagger-coverage-output directory:"
          ls -la swagger-coverage-output || echo "Output folder not found"

      - name: Archive Swagger coverage report
        uses: actions/upload-artifact@v4
        with:
          name: swagger-coverage-report
          path: "swagger-coverage-report-dm_api_account.html"
          if-no-files-found: warn

      - name: Archive allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 1

  generate-report:
    runs-on: ubuntu-latest
    needs: test
    name: Generate report
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'
      - run: sudo wget https://github.com && sudo tar -xvzf allure-2.29.0.tgz -C /opt/ && sudo ln -s /opt/allure-2.29.0/bin/allure /usr/bin/allure
      - name: Download allure results
        uses: actions/download-artifact@v4
      - run: allure generate -c allure-results -o _site --clean
      - name: Store report
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path: _site
          retention-days: 1

  publish-report:
    runs-on: ubuntu-latest
    needs: generate-report
    permissions:
      pages: write
      id-token: write
    name: Publish report
    steps:
      - uses: actions/checkout@v4
      - name: Download site report
        uses: actions/download-artifact@v4
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v4
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - run: echo "https://maratsayfutdinov7.github.io"

